version: "3.8"

services:
  db:
    image: postgres:16.4 # Usando PostgreSQL 16.4
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always # Reinicia automaticamente o container em caso de falha ou reinicialização do sistema

  api:
    build:
      context: .
      dockerfile: Dockerfile # Certifique-se de ter um Dockerfile configurado para a aplicação Node.js
    container_name: fastify_api_container
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    restart: always # Reinicia automaticamente o container em caso de falha ou reinicialização do sistema

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
